// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "Colour",
  platforms: [
    .iOS("16.0"),
  ],
  products: [
    .iOSApplication(
      name: "Colour",
      targets: ["AppModule"],
      bundleIdentifier: "llc.goodhats.colour",
      teamIdentifier: "QC68T7ZF53",
      displayVersion: "0.0.1",
      bundleVersion: "1",
      appIcon: .placeholder(icon: .palette),
      accentColor: .presetColor(.pink),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ],
      capabilities: [
        .photoLibrary(purposeString: "Import images for colour sampling"),
        .fileAccess(.userSelectedFiles, mode: .readWrite),
        .fileAccess(.pictureFolder, mode: .readWrite),
      ],
      appCategory: .developerTools
    ),
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      path: ".",
      swiftSettings: [
        .enableUpcomingFeature("BareSlashRegexLiterals"),
      ]
    ),
  ]
)
